export const tokens = {
    colors: {
        bgPrimary: '#F6F8FC',
        bgSecondary: '#FFFFFF',
        bgCard: '#FFFFFF',
        bgElevated: '#F9FAFF',
        primary: '#2F18F6',
        primaryHover: '#432DFF',
        accent: '#5B6CFF',
        success: '#16A34A',
        warning: '#D97706',
        danger: '#DC2626',
        border: 'rgba(15,23,42,0.10)',
        textPrimary: '#0F172A',
        textSecondary: '#475569',
        textMuted: '#8390A3',
    },
    sidebar: {
        width: 280,
        widthCollapsed: 80,
        bg: '#FFFFFF',
        borderColor: 'rgba(15,23,42,0.10)',
    },
    header: {
        height: 64,
        bg: '#FFFFFF',
        borderColor: 'rgba(15,23,42,0.10)',
    },
    borderRadius: {
        sm: 6,
        md: 10,
        lg: 14,
        xl: 18,
    },
    font: {
        family: "'Inter', -apple-system, BlinkMacSystemFont, 'Segoe UI', Roboto, sans-serif",
        size: {
            xs: 12,
            sm: 13,
            md: 14,
            lg: 16,
            xl: 20,
            xxl: 24,
        },
        weight: {
            regular: 400,
            medium: 500,
            semibold: 600,
            bold: 800,
        },
    },
    spacing: {
        xs: 4,
        sm: 8,
        md: 16,
        lg: 24,
        xl: 32,
        xxl: 48,
    },
} as const;